### ISSUE TITLE
Base on MLX-C instead?

### ISSUE THREAD

**Issue by dcvz** [oxideai/mlx-rs#20]
MLX has created a C API that they based their Swift version on. Is there any benefit here on using that as the base?

Separately, is there a Discord or community for `mlx-rs` for those that want to contribute - to organize work?

**Comment by minghuaw** [comment]
I haven't checked out the C bindings yet. The rust binding is remaining in the preview releases mainly because `mlx` is doing weekly releases that often come with breaking changes. I was planning to wait for a more or less stable upstream release before dedicating more time on the rust binding.

I haven't set up a discord for this yet. I'll be happy to set up one if you are interested in contributing.

A big problem with the mlx c++ code is that the high level neural net abstractions are all written in python, and this makes the current binding to the c++ code is not that useful.

**Comment by minghuaw** [comment]
I have just taken a very superficial look at the C API and mlx-swift, and it seems you could achieve a lot more with the swift binding. So it's probably a good idea to switch to the C API. I have just set up a discord server (https://discord.gg/2P9Bh3GW), feel free to join, and we could probably coordinate the work if you are interested

**Comment by minghuaw** [comment]
Looks like the swift binding simply re-implemented the neural net layer stuff (https://github.com/ml-explore/mlx-swift/blob/129f95ac965eb66be0e8ea4680e5ae78be84761e/Source/MLXNN/Module.swift#L98). 

But switching to C API may still be beneficial, as we could more easily get around the cumbersomeness with all the `Cxx*` types

**Comment by minghuaw** [comment]
Asked why `nn.Module` is only implemented in Python on their discord server (https://discord.com/channels/1210352300812673094/1210352300812673097/1228839956256915607) and got the following response.

> It’s a good question. Mostly because at that level the implementation is more language specific.
> We rely on pythonic idioms for the Python NN to make it easy to use. Same for Swift
> Perf is not so much affected. Downside is you have to reimplement stuff. We may do a Cpp version in the future if that becomes tedious

Seems like whether or not the rust binding switches to the C API, we will have to re-implement the neural net primitives anyway

**Comment by edfix** [comment]
I'm thrilled to see another Rust binding for MLX taking shape. I've been working on a [binding](https://github.com/edfix/mlx-rust) based on MLX-C myself and have achieved preliminary support for Phi2. Although the current API is still a bit unrefined and requires further polishing, there's a significant amount of work yet to be done. I'm very much looking forward to exchanging ideas and collaborating with you.

**Comment by minghuaw** [comment]
Closing this issue as we have made the first release based on the c binding
